[project]
name = "a-small-python-project"
version = "0.1.0"
description = "This project consists into transforming an input image into a svg file."
readme = "README.md"
authors = [
    { name = "Thomas Belliot", email = "thomas.belliot@centrale.centralelille.fr" }
]
requires-python = ">=3.12"

packages = ["src/a_small_python_project"]

dependencies = [
    "pillow>=12.3.0",
]

[project.scripts]
a-small-python-project = "a_small_python_project:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "marimo>=0.25.1",
    "mypy>=2.4.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.10",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
